services:

  app:
    build:
      context: ./app

    container_name: ai-devsecops-app

    ports:
      - "8000:8000"

  prometheus:
    image: prom/prometheus

    container_name: prometheus

    ports:
      - "9090:9090"

    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml