apiVersion: v1
kind: Service

metadata:
  name: ai-devsecops-service
  namespace: ai-devsecops

spec:
  selector:
    app: ai-devsecops

  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

  type: NodePort